### ISSUE TITLE
'NoneType' object has no attribute 'train'

### ISSUE THREAD

**Issue by Lxhnnn** [YLonely/Web-Data-Mining#1]
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.914 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "example.py", line 21, in <module>
    eva.evaluate(algo=lsi, k=k_list, n_jobs=n_jobs, split_date='2014-3-21', auto_log=True, debug=True)
  File "/data/lxh/web-data-mining-master/ucas_dm/utils.py", line 45, in evaluate
    algo.train(train_set)
  File "/data/lxh/web-data-mining-master/ucas_dm/prediction_algorithms/topic_based_algo.py", line 93, in train
    self._content_algo.train(train_set)
AttributeError: 'NoneType' object has no attribute 'train'

**Comment by Lxhnnn** [comment]
lsi有问题，lda没问题
